linters:
  enable:
    - bodyclose
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - nakedret
    - godox
  disable:
    - funlen
    - nestif
    - forcetypeassert
  presets:
    - bugs
    - comment
    - complexity
  fast: true