services:
  app:
    build: ./
    container_name: merch-shop
    environment:
      CONFIG_PATH: internal/configure/stage.yaml
    volumes:
      - .internal/configure/stage.yaml:/internal/configure/stage.yaml
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - merch_net


  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: merch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U yks" ]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      merch_net:
        aliases:
          - database


networks:
  merch_net:

volumes:
  data:
